# Author: Johan Sydseter <johan.sydseter@startsiden.no>
---
autoinstallver: 1
name: vagrant-sydseter-debian-wheezy-amd64-demo
version: 13.02.01-01

exludeext:
  - .md
  - .git
  - .gitignore
  - .gitmodules

installto:
  doc: /usr/share/doc/vagrant-sydseter-debian-wheezy-amd64-demo
  bin: /usr/local/bin

depends:
  - virtualbox
  - vagrant
  - git

excludedir:
  - utils

installdir: /usr/local/etc/vagrant-sydseter-debian-wheezy-amd64-demo

tests: t/
test_requires:
  - sudo
  - build-essential
  - linux-headers-3.2.0.4-amd64
  - virtualbox-guest-utils
  - ssh
  - libtest-bdd-cucumber-perl
